// <auto-generated />
namespace DemoApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddINvoice123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddINvoice123));
        
        string IMigrationMetadata.Id
        {
            get { return "201809230828411_AddINvoice123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
